### PR TITLE
Fix demo files

### PR DESCRIPTION
**Pull request by tylersimko**
This is nearly everything, how does it look? A few quick things:

1. `women` is used by another R dataset, so I used `data(women, package = "qss")`
2. Prediction isn't up because `primary2008` is no longer a column in `social.` I'm not sure what's happening here, was it removed?
3. Probability isn't here because I couldn't find the `fit1` object from Chapter 4 saved anywhere. How should I load this in? 
4. Do we have a style preference between `data("social")` and `data(social)`? Both seem to work fine. 
5. Since the data is loaded in, I had to fix some naming inconsistencies, like changing `names` to `cnames` and `FLCensusVTD` to `FLCensus`. I just renamed them and removed the old one from memory in the file, but if you'd like to do it a different way let me know.

### CODE REVIEW

**Comment by kosukeimai** [comment]
1.  Sounds good.  Why don't we always add `package = "qss"` to avoid ambiguity?
2. This is an error. See #13 of `qss` repo.  We need to change in the code from `primary2008` to `primary2006` Can you make the correction in the `qss` repo too?
3. What about including the code that was used to produce `fit1`?
4. Let's go without quotation but see point 1 above.
5. Are these inconsistencies present in the `qss` repo?  The book itself?

**Comment by tylersimko** [comment]
1-4. Sounds good, will do. 
5. It's not a problem with either. It just happens when the object name you chose in the book doesn't match the original data file name. For example, in the book you use: 

`cnames <- read.csv("names.csv")`

In these demos we have to use `data(names)`, but the remaining demo code still uses `cnames` (since I took it from the book).

**Comment by kosukeimai** [comment]
I see. I should have used the file name `cnames.csv` in the book!  We should use `cnames` in the demo to be consistent with the book.

**Comment by tylersimko** [comment]
Okay, I just converted the name like this: 

```
data(names)
cnames <- names # rename
rm(names) # remove
```

Let me know if I should do it a different way. I'll add the `package = "qss" too.

**Comment by kosukeimai** [comment]
Can we just save the data as `cnames`?

**Comment by jrnold** [comment]
Using `cnames` is a good idea. Also, since the data are lazy-loaded, you don't need to use `data()`. You can also refer to the data frames by prefixing them with `::` without having to load the library. E.g. `qss::names`.

**Comment by tylersimko** [comment]
Okay, then should I just change the filenames from `names` to `cnames` in `data/` and `data-raw/`? I wasn't sure if they had to stay the same in the file system you set up. 

Pedagogically, it might be better to include `data()` even if it's not explicitly needed so students understand we're loading data in before using it (since the lazy-loading process isn't described in the book). What do you think @kosukeimai?

**Comment by kosukeimai** [comment]
Yes let's go with `data()` since then the rest of the code stays identical to the one in the book.

**Comment by jrnold** [comment]
Regarding `data("social")` and `data(social)`, it's totally preference but it is a weird quirk of R that it uses non-standard evaluation with `data()` and `library()` so that it uses non-standard evaluation, and interprets unquoted names and searches for them among the list of packages or data-sets. Inevitably, some student will ask about it.

**Comment by jrnold** [comment]
The issue with `FLCensus` is that the csv file is assigned to a different name:
```r
FLCensus <- read.csv("FLCensusVTD.csv")
```
I'll adjust `build.R` to add a special case.

**Comment by jrnold** [comment]
I updated `build.R` to rename `names` to `cnames` and `FLCensusVTD` to `FLCensus`.

**Comment by jrnold** [comment]
@tylersimko @kosukeimai See #11 as an alternative to using demo scripts (which I don't think are particularly good). It creates R markdown files from the R scripts to use as vignettes.

**Comment by kosukeimai** [comment]
Let's do vignettes.  Thanks.

**Pull request merged**
