### PR TITLE
add vigette example

### PR DESCRIPTION
**Pull request by jrnold**
This takes one of the scripts in `demo` and converts it to a Rmd file in `vignettes`. I lightly edited the `.R` script to give it a yaml header and have markdown headers and knitr comments: see [reports from R scripts](http://rmarkdown.rstudio.com/articles_report_from_r_script.html). Then I use `knitr::spin()` to convert the `.R` file to an `.Rmd` file, which is usable as a vignette. This looks good, and also appears has the nice side effect of appearing in the pkgdown site.

### CODE REVIEW

**Comment by kosukeimai** [comment]
I agree.  Let's go with vignettes.

**Comment by jrnold** [comment]
I merged the changes from `demos` into the `vignettes`. I moved the scripts from `demo` to `inst/scripts`. Edit the `*.R` files, and then use `data-raw` to convert them to `*.Rmd` files that reside in `vignettes/`.  I added the necessary boilerplate for R to recognize them as vignettes but I didn't do anything to debug them and get them running.

For maintainability, it may be a good idea to figure out how to have a single copy of the scripts between `qss` and `qss-package` and use scripts to convert between them, so that any bugs or manual edits only have to be done in one location.

**Comment by kosukeimai** [comment]
Yes I agree about having one location. Ideally, I would like to use qss to be that repo and pull the necessary info from that repo to qss-package. Is that possible.

**Comment by kosukeimai** [comment]
What do you think about the idea of incorporating your tidyverse code as vignettes?

**Comment by jrnold** [comment]
Sure. As long as the code remains open, and I'm able to edit it. You should probably merge this branch, and I'll vignettes with tidyverse code later. I have to find time or assign someone to take the existing code and clean it up (remove non-relevant notes and comments).

**Comment by kosukeimai** [comment]
Yes, this package will remain open

**Pull request merged**
