### PR TITLE
Add data

### PR DESCRIPTION
**Pull request by tylersimko**
Here are the updated data descriptions. A few notes:

* `florentine.csv`: Should there be a description for the family names (columns)?
* `chechen.csv`, `resources.csv`: Don't have tables in the book.  I think we removed these from the qss repo when working on it earlier. 
* There's a column called `han` in `chinawomen.csv` that isn't documented in the table. 
* There's a column called `l_x` in the Kenya, Sweden, World files that isn't documented in the table.

### CODE REVIEW

**Comment by kosukeimai** [comment]
Thanks for this.  A few comments: 

1. Can you add a title and short description of the data?  The title is available as the title of the corresponding table in the book.  You will have to come up with one sentence description of the data.  The example is given here: http://r-pkgs.had.co.nz/data.html

2. `florentine.csv` has family names for both columns and rows, right? 

3. Those additional data sets need to be removed from the `qss` repo as well as this repo.

4. If the `han` and `l_x` variables are not used in the book (for exercises, check out the solutions at `qss-inst` repo), then they should be removed from the original data sets in `qss` repo.  Once the corrections are made to the original data sets in `qss` repo, we can pull it into this repo using @jrnold's code.

**Comment by tylersimko** [comment]
1. Got it, will do. 

2. Yes, it's the adjacency matrix in the network data section. 

3. I'll do that now. 

4. Okay, I'll take care of the other things first then try to figure this out.

**Comment by kosukeimai** [comment]
I'm not sure about 4: maybe just copy those modified files over to this repo. I'm inviting @jrnold who can help you out with this.  You should also add yourself as an author of this package: we go alphabetical.

**Comment by jrnold** [comment]
Here was the workflow I used in order to separate the data from the presentation in the documentation.  All raw data was and it's processing was included in `data-raw`, which has become a common convention in[ R packages](http://r-pkgs.had.co.nz/data.html). Everything, both `.rda` files, `.R` files and `.Rd` documentation files, are built from the csv or other sources using the build scripts.

`build.R` uses readr `read_csv`. I like it because it is a little faster, and also simultaneously more strict about column types, and more forgiving in that it has datetime column parsers that work well. For each csv file I have a file `spec/*.R` which specifies the column types in the csv. The build script will actually generate these if one doesn't exists, and then you can edit it afterwards if columns are not recognized correctly.

`build.R` also generates the `.R` files for each dataset. I wasn't crazy enough to manually enter the number of rows and columns in each data frame. The relevant code in `build.R` is [here](https://github.com/kosukeimai/qss-data/blob/cec4b1ff92d980d7ce5ff21e8f7ffa1277c51463/data-raw/build.R#L60).  Each `.R` file for a dataset is generated from a template: [data-raw/doc-template](https://github.com/kosukeimai/qss-data/blob/master/data-raw/doc-template.R). This template is used with the [whisker](https://github.com/edwindj/whisker) R package. Anything inside the `{{ }}` is replaced with variables. I generate those variables from metadata about each dataset in `data-raw/qss-data.yaml` (title, name, location in the book) and the dataset itself (variable names, variable types, number of rows and columns).   To add variable descriptions you could add the metadata to `data-raw/qss-data.yaml` and then adjust the template. 

There's a few advantages of this approach. First, you aren't rewriting documentation that follows a fairly common format. Second, you can include tests in the build process to check for issues. If columns are added, removed, or renamed, you can include logic in `build.R` to check that all columns have a description.

**Comment by tylersimko** [comment]
How do these descriptions look? @jrnold's script automatically pulled in the titles, but I basic one-line descriptions. Is there anything else I should put in the documentation? Here's an example:

`STAR.csv`: Contains data from the STAR (Student–Teacher Achievement Ratio) Project, a four-year longitudinal study examining the effect of class size in early grade levels on educational performance and personal development.

**Comment by kosukeimai** [comment]
Looks great.  Let's add the references (with the doi link) where the data originally come from.  For exercises, you can grab them from the Rmarkdown file in `qss-inst`.  For the data sets that appear in the main text, you will find the references in the main text (in a footnote where the study is introduced).  Thanks.

**Comment by tylersimko** [comment]
Okay, I'll add references in the Details section. I'll use the doi links in the Rmarkdown files, but it doesn't look like every reference in the textbook has one - I'll find the rest online.

**Comment by kosukeimai** [comment]
Right.  You should be able to find them online though.  Thanks.

**Comment by tylersimko** [comment]
Here are all the ones I found; I included all of the references in the textbook and all of the ones from the exercises that have datasets in this package.

**Comment by kosukeimai** [comment]
Great.  Is there anyone that is missing?

**Comment by tylersimko** [comment]
@jrnold might be able to clarify, but to me it looks like the package currently contains data sets mentioned in the book itself, not all of the additional exercises in `qss-inst` (some from that repo are included because they are used in the textbook as well).

**Comment by kosukeimai** [comment]
Right.  That's correct since only instructors have access to those additional exercises.

**Comment by jrnold** [comment]
I only pulled in the data sets from the qss repo. That's why the qss repo is the only one that's a submodule of this. The build script [https://github.com/kosukeimai/qss-data/blob/master/data-raw/build.R](build.R) finds all `.csv` files in its subdirectories.

**Comment by jrnold** [comment]
What's going to be considered the true copy of the data? Is it the `.rda` files in this package, the `.csv` files in this package, `.csv` files in the `qss` repo? If there isn't one true copy somewhere, with scripts building all other derivatives, then any manual update of multiple locations is bound to generate errors.

**Comment by tylersimko** [comment]
Perfect. Then I included references and updated documentation for all of those datasets. 

These do not have citations mentioned in the textbook: `FLCensusVTD.csv`, `UNpop.csv`, `USGini.csv`, `elections.csv`, `florentine.csv`, `florida.csv`, `names.csv`, `polls08.csv`, `polls12.csv`, `twitter.following`, `twitter.senator`. 

All of the rest have references to articles or sources.

**Comment by jrnold** [comment]
You should `data-raw/build.R` to be consistent with the new changes, and establish what the workflow is for adding new datasets. Right now `data-raw/build.R` writes out the `R/*.R` files, so if run again, it will clobber your changes.

**Comment by kosukeimai** [comment]
We will be using the data in the `qss` repo as the true copy.

> What's going to be considered the true copy of the data? Is it the .rda
> files in this package, the .csv files in this package, .csv files in the
> qss repo? If there isn't one true copy somewhere, with scripts building
> all other derivatives, then any manual update of multiple locations is
> bound to generate errors.

**Comment by kosukeimai** [comment]
`FLCensusVTD.csv` (also `names.csv`) and `florentine.csv` should have the references (studies that are mentioned in those sections are the ones).  For `twitter.following` and `twitter.senator`, you can reference https://academic.oup.com/pan/article-abstract/23/1/76/2755421/Birds-of-the-Same-Feather-Tweet-Together-Bayesian?redirectedFrom=fulltext

`UNpop.csv`, `USGini.csv`, `florida.csv`, `elections.csv` don't have references. 

`polls08.csv`, `polls12.csv` come from http://elections.huffingtonpost.com/pollster and so let's reference that.

**Comment by kosukeimai** [comment]
@jrnold What's the workflow you recommend?  Can you help @tylersimko on this?  Thanks.

**Pull request merged**
